let topics = [
    "In one sentence, how would you sum up the internet?",
    "What sport would be the funniest to add a mandatory amount of alcohol to?",
    "There's this special room that when you go inside for one hour, it's equivalent to one year. You have a chance to go there for one hour, which skill would you choose to practice/learn there in order to master it?",
    "What would be the worst thing for the government to make illegal?",
    "What are some fun and interesting alternatives to war that countries could settle their differences with?",
    "What was the funniest TV show you watched growing up?",
    "If you could instantly become a circus character, what would it be?",
    "If your life was a movie, what would be the title?",
    "If you could only eat one food for the rest of your life, what would it be?",
    "What is the craziest, most adventurous thing you’ve ever done?",
    "If you won the lottery, what’s the weirdest thing you would buy?",
    "Do you believe in ghosts or extraterrestrial life?",
    "If you could eliminate one thing from your daily routine, what would it be and why?",
    "What was your dream job as a kid?",
    "What three things would you do if you were invisible?",
    "What is the best prank you’ve experienced or planned?",
    "What’s your favorite animal?",
    "Tell us about a sport that you would recommend to everyone.",
    "What's your favorite hobby?",
    "What do you think about the supernatural/ghosts/energy?",
    "Tell us one thing that you do when you are sad that automatically helps to bring some joy.",
    "Do you have a dream job?",
    "You won 1million dollars. What’s the first material thing you would buy?",
    "What’s your opinion on AI and the impact it may have in our future?",
    "Sweet or savory?",
    "Documentaries. Yes or no?",
    "Do you prefer summer or winter?",
    "What's your favorite thing to do on a lazy day?",
    "Is One Long Vacation Better Than Many Short Breaks?",
    "Do you have any phobias?",
    "Should Schools Teach More About Practical Skills?",
    "Should Schools Focus More on Creativity or Discipline?",
    "Gap Year: A Wise Choice or a Delay Tactic?",
    "Should Schools Embrace Online Learning Fully?",
    "Have you ever traveled to a foreign country? Where did you go?",
    "If aliens visited Earth and you were the first person they met, how would you explain your job?",
    "If you could have any talent, what would you choose?",
    "Would you survive a zombie apocalypse?",
    "What’s the silliest goal you’ve ever set for yourself?",
    "Movie theater or streaming at home?",
    "What’s your favorite holiday?",
    "What is your all-time favorite food?",
    "What’s your favorite place to eat around [neighborhood]?",
    "Describe your perfect vacation destination.",
    "What is the most important invention of the last 100 years?",
    "Share your thoughts on social media’s influence on society.",
    "Talk about a book that changed your perspective on life.",
    "What is your favorite season of the year and why?",
    "Discuss the benefits of learning a second language.",
    "What is your stance on climate change and its effects?",
    "What is your favorite childhood memory?",
    "Talk about the role of technology in education.",
    "What are the advantages and disadvantages of remote work?",
    "Share your thoughts on the importance of mental health.",
    "What is a skill you’d like to learn and why?",
    "Discuss the impact of music on your life.",
    "Explain the importance of exercise and physical fitness.",
    "What are your thoughts on space exploration?",
    "Describe a time when you overcame a significant challenge.",
    "What is your favorite holiday and why?",
    "Talk about the importance of community service.",
    "Describe a hobby you enjoy and why.",
    "What is your opinion on the current education system?",
    "Share your thoughts on the importance of family.",
    "What is your favorite quote and why?",
    "Discuss the benefits of traveling.",
    "Describe your dream home.",
    "Talk about the importance of empathy in today’s world.",
    "What is your favorite genre of music and why?",
    "Explain the role of art in society.",
    "What is the best advice you’ve ever received?",
    "Discuss the impact of sports on personal development.",
    "What is your opinion on the future of transportation?",
    "What is your favorite form of exercise and why?",
    "Share your thoughts on the importance of sleep.",
    "Talk about the benefits of meditation and mindfulness.",
    "Describe your favorite place to relax.",
    "What is your opinion on renewable energy?",
    "Discuss the impact of fashion on culture.",
    "What is your favorite way to spend a weekend?",
    "Explain the importance of financial literacy.",
    "What are your thoughts on the future of work?",
    "Describe a person who has had a significant impact on your life.",
    "What is your favorite type of food and why?",
    "Talk about the benefits of having a pet.",
    "What is your opinion on the role of government in society?",
    "Describe your favorite childhood game.",
    "What are your thoughts on the future of healthcare?",
    "Explain the importance of self-care.",
    "What is your favorite way to stay motivated?",
    "Discuss the impact of movies and TV shows on culture.",
    "What is your opinion on public transportation?",
    "Describe a place you’d like to visit and why.",
    "What are your thoughts on the importance of networking?",
    "Talk about the benefits of lifelong learning.",
    "What is your favorite holiday tradition?",
    "Explain the importance of goal setting.",
    "What are your thoughts on the future of education?",
    "Describe a memorable event in your life.",
    "What is your opinion on the impact of social media on mental health?",
    "Talk about the benefits of outdoor activities.",
    "What is your favorite type of weather and why?",
    "Explain the importance of teamwork.",
    "What are your thoughts on the future of technology?",
    "Describe a skill you have mastered and how you did it.",
    "What is your opinion on the importance of cultural diversity?",
    "Talk about the benefits of reading.",
    "What is your favorite way to de-stress?",
    "Explain the importance of communication skills.",
    "What are your thoughts on the impact of artificial intelligence?",
    "Describe your ideal job.",
    "What is your opinion on the importance of volunteering?",
    "Talk about the benefits of positive thinking.",
    "What is your favorite way to stay active?",
    "Explain the importance of time management.",
    "What are your thoughts on the future of the environment?",
    "What is your opinion on the impact of technology on relationships?",
    "Talk about the benefits of healthy eating.",
    "What is your favorite type of vacation and why?",
    "Explain the importance of resilience.",
    "What are your thoughts on the impact of globalization?",
    "What is your opinion on the importance of creativity?",
    "Talk about the benefits of being organized.",
    "What is your favorite type of book and why?",
    "Describe a habit you’d like to break and why.",
    "What is your opinion on the impact of sports on society?",
    "Talk about the benefits of being outdoors.",
    "What is your favorite type of art and why?",
    "Explain the importance of self-discipline.",
    "What are your thoughts on the impact of science on society?",
    "Describe a person you admire and why.",
    "What is your opinion on the importance of innovation?",
    "Talk about the benefits of practicing gratitude.",
    "What is your favorite way to spend time with friends?",
    "Explain the importance of personal growth.",
    "What are your thoughts on the future of space exploration?",
    "Describe a goal you’re working towards.",
    "What is your opinion on the impact of technology on privacy?",
    "Talk about the benefits of maintaining a work-life balance.",
    "What is your favorite type of technology and why?",
    "Explain the importance of adaptability.",
    "What are your thoughts on the impact of education on society?",
    "Describe a lesson you’ve learned from failure.",
    "What is your opinion on the importance of ethical leadership?",
    "Talk about the benefits of practicing mindfulness.",
    "What is your favorite way to spend a rainy day?",
    "Explain the importance of setting boundaries.",
    "What are your thoughts on the impact of cultural exchange?",
    "Describe a memorable trip you’ve taken.",
    "What is your opinion on the importance of digital literacy?",
    "Talk about the benefits of a healthy lifestyle.",
    "What is your favorite way to celebrate achievements?",
    "Explain the importance of emotional intelligence.",
    "What are your thoughts on the impact of technology on education?",
    "Describe a hobby you’d like to try and why.",
    "What is your opinion on the importance of sustainable living?",
    "Talk about the benefits of being proactive.",
    "What is your favorite way to spend a day off?",
    "Explain the importance of self-awareness.",
    "What are your thoughts on the impact of social change movements?",
    "Describe a challenge you’ve faced and how you overcame it.",
    "What is your opinion on the importance of health and wellness?"
];

let usedTopics = [];

function generateRandomTopic() {
    const topicElement = document.getElementById("topic-list");

    // Iniciar animação de roleta
    topicElement.style.transition = "transform 1s ease-in-out";  // Animação mais rápida
    topicElement.style.transform = "translateY(-200%)";  // Movendo para cima rapidamente

    setTimeout(() => {
        let availableTopics = topics.filter(topic => !usedTopics.includes(topic));
        if (availableTopics.length === 0) {
            availableTopics = [...topics];  // Se todos os tópicos foram usados, resetar
            usedTopics = [];
        }

        // Escolher um tópico aleatório
        const randomTopic = availableTopics[Math.floor(Math.random() * availableTopics.length)];

        // Atualizar o conteúdo com o tópico
        topicElement.innerHTML = `<span class="topic-item">${randomTopic}</span>`;

        // Adicionar o tópico à lista de usados
        usedTopics.push(randomTopic);

        // Resetar a animação (voltar à posição inicial)
        topicElement.style.transform = "translateY(0)";  // Retornar ao topo após animação
    }, 1000);  // Tempo de animação (1 segundo)
}
